### PR TITLE
Feature/new aside

### PR DESCRIPTION
**Pull request by builtbyedgar**

### CODE REVIEW

**Comment by martejpad** [comment]
@builtbyedgar is this ready for review? 

not sure if this PR fixes the problem with the menu, I can see it is still there:

**Comment by martejpad** [comment]
@builtbyedgar is this ready for review?

Does this PR fixes the problem with the menu in the home page?

Thanks!

**Review by borja-munoz — COMMENTED** [review]
LGTM.

The only thing missing is the scroll bar in the desktop mode (it works in the mobile mode).

**Comment by builtbyedgar** [comment]
Right, I'll fix it and upload it to this branch

**Comment by builtbyedgar** [comment]
On the other hand, the header submenu needs to be fixed. I've already discovered the bug   :bug:

**Comment by borja-munoz** [comment]
The fixes look good to me (navbar menu and scroll bar) but I've found a couple of additional minor issues in the responsive view:

- The link to the code repo is partially hidden
- The full screen button in the layout example overlaps with the attribution button

Screenshot 2021-07-05 at 10 08 27

**Pull request merged**
